/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import Controller.PatronCtrl;
import java.awt.Color;
import java.util.Date;
import java.text.SimpleDateFormat;
import java.util.Arrays;
import java.util.Random;
import javax.swing.JOptionPane;
import model.Patron;

/**
 *
 * @author Admin
 */
public class FDangKi extends javax.swing.JFrame {
    private boolean[] check = new boolean[5];// mảng boolean để check xem các trường được điền chưa
    
    
    private String taoMaKH() {
        Date currentDate = new Date();
        SimpleDateFormat sdf = new SimpleDateFormat("MMddHHmmss");
        Random rd = new Random();
        StringBuilder rs = new StringBuilder();
        rs.append("ptr");
        rs.append(sdf.format(currentDate));
        rs.append(rd.nextInt(100));
        return rs.toString();
    }

    /**
     * Creates new form FDangKi
     */
    public FDangKi() {
        initComponents();
        this.tfPatronID.setText(taoMaKH());
        this.tfFName.requestFocus();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tfPatronID = new javax.swing.JTextField();
        LbFName = new javax.swing.JLabel();
        LbLName = new javax.swing.JLabel();
        tfLName = new javax.swing.JTextField();
        tfFName = new javax.swing.JTextField();
        LbEmail = new javax.swing.JLabel();
        LbPass = new javax.swing.JLabel();
        LbRePass = new javax.swing.JLabel();
        tfEmail = new javax.swing.JTextField();
        ckAgree = new javax.swing.JCheckBox();
        btDangKi = new javax.swing.JButton();
        btResetMaKH = new javax.swing.JButton();
        pfRePass = new javax.swing.JPasswordField();
        pfPass = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Đăng kí");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Mã khách hàng:");
        jLabel1.setToolTipText("");

        tfPatronID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tfPatronID.setEnabled(false);

        LbFName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LbFName.setText("Họ:");
        LbFName.setToolTipText("");

        LbLName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LbLName.setText("Tên:");
        LbLName.setToolTipText("");

        tfLName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tfLName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfLNameFocusLost(evt);
            }
        });
        tfLName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfLNameActionPerformed(evt);
            }
        });

        tfFName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tfFName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfFNameFocusLost(evt);
            }
        });
        tfFName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfFNameActionPerformed(evt);
            }
        });

        LbEmail.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LbEmail.setText("Email:");
        LbEmail.setToolTipText("");

        LbPass.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LbPass.setText("Pass:");
        LbPass.setToolTipText("");

        LbRePass.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LbRePass.setForeground(new java.awt.Color(0, 0, 255));
        LbRePass.setText("Re-Pass");
        LbRePass.setToolTipText("");

        tfEmail.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tfEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfEmailFocusLost(evt);
            }
        });
        tfEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfEmailActionPerformed(evt);
            }
        });

        ckAgree.setText("Yêu cuộc sống này");
        ckAgree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckAgreeActionPerformed(evt);
            }
        });

        btDangKi.setText("Đăng kí");
        btDangKi.setEnabled(false);
        btDangKi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDangKiActionPerformed(evt);
            }
        });

        btResetMaKH.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btResetMaKH.setText("R");
        btResetMaKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btResetMaKHActionPerformed(evt);
            }
        });

        pfRePass.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pfRePass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                pfRePassFocusLost(evt);
            }
        });
        pfRePass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pfRePassActionPerformed(evt);
            }
        });

        pfPass.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pfPass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                pfPassFocusLost(evt);
            }
        });
        pfPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pfPassActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(ckAgree)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LbLName)
                            .addComponent(LbFName))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfLName)
                            .addComponent(tfFName)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LbEmail)
                        .addGap(18, 18, 18)
                        .addComponent(tfEmail))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btDangKi, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LbPass)
                        .addGap(25, 25, 25)
                        .addComponent(pfPass, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(tfPatronID, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btResetMaKH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LbRePass)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pfRePass)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btResetMaKH, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfPatronID)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbFName)
                    .addComponent(tfFName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbLName)
                    .addComponent(tfLName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbEmail)
                    .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LbPass)
                    .addComponent(pfPass, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LbRePass)
                    .addComponent(pfRePass, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(ckAgree)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btDangKi, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btResetMaKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btResetMaKHActionPerformed
        // TODO add your handling code here:
        this.tfPatronID.setText(taoMaKH());
    }//GEN-LAST:event_btResetMaKHActionPerformed

    private void tfFNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfFNameFocusLost
        // TODO add your handling code here:
        if (this.tfFName.getText().isEmpty()) {
            check[0] = false;
            this.LbFName.setForeground(Color.red);
        }else{
            check[0] = true;
            this.LbFName.setForeground(Color.black);
        }
    }//GEN-LAST:event_tfFNameFocusLost

    private void tfLNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfLNameFocusLost
        // TODO add your handling code here:
        if (this.tfLName.getText().isEmpty()) {
            check[1] = false;
            this.LbLName.setForeground(Color.red);
        }else{
            check[1] = true;
            this.LbLName.setForeground(Color.black);
        }
    }//GEN-LAST:event_tfLNameFocusLost

    private void tfEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfEmailFocusLost
        // TODO add your handling code here:
        if (this.tfEmail.getText().isEmpty()) {
            check[2] = false;
            this.LbEmail.setForeground(Color.red);
        }else{
            check[2] = true;
            this.LbEmail.setForeground(Color.black);
        }
    }//GEN-LAST:event_tfEmailFocusLost

    private void pfPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pfPassActionPerformed
        // TODO add your handling code here:
        this.pfRePass.requestFocus();
    }//GEN-LAST:event_pfPassActionPerformed

    private void ckAgreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckAgreeActionPerformed
        // TODO add your handling code here:
        if(this.ckAgree.isSelected()){
            int i =0;
            for(i = 0 ; i <5 ; i++){
                if(this.check[i] == false){
                    this.ckAgree.setSelected(false);
                    break;
                }
            }
            if(i == 5){
                this.btDangKi.setEnabled(true);
            }
        }
        
    }//GEN-LAST:event_ckAgreeActionPerformed

    private void pfPassFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pfPassFocusLost
        // TODO add your handling code here:
         if (this.pfPass.getPassword().length == 0) {
             check[3] = false;
            this.LbPass.setForeground(Color.red);
        }else{
             check[3] = true;
            this.LbPass.setForeground(Color.black);
        }
    }//GEN-LAST:event_pfPassFocusLost

    private void pfRePassFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pfRePassFocusLost
        // TODO add your handling code here:
        boolean isSame = true;
        char[] pass = pfPass.getPassword();
        char[] repass = pfRePass.getPassword();
        if (pass.length != repass.length) {
            this.LbRePass.setForeground(Color.red);
            check[4] = false;
            return;
        }
        for(int i = 0; i < pass.length; i++){
            if(pass[i] != repass[i]){
                this.LbRePass.setForeground(Color.red);
                check[4] = false;
            return;
            }
        }
        this.LbRePass.setForeground(Color.BLACK);
        check[4] = true;
    }//GEN-LAST:event_pfRePassFocusLost

    private void btDangKiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDangKiActionPerformed
        // TODO add your handling code here:
        String hashPass = PatronCtrl.encryptPassword(Arrays.toString(this.pfPass.getPassword()));
       Patron p = new Patron();
       p.setFirstName(this.tfFName.getText());
       p.setLastName(this.tfLName.getText());
       p.setPatronID(this.tfPatronID.getText());
       p.setPass(hashPass);
       p.setEmail(this.tfEmail.getText());
       PatronCtrl pctrl = new PatronCtrl();
       if(pctrl.themKH(p)){
           JOptionPane.showMessageDialog(rootPane, "Them thanh cong!");
           this.dispose();
       }else{
           JOptionPane.showMessageDialog(rootPane,"Them that bai!");
       }
    }//GEN-LAST:event_btDangKiActionPerformed

    private void tfFNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfFNameActionPerformed
        // TODO add your handling code here:
        this.tfLName.requestFocus();
    }//GEN-LAST:event_tfFNameActionPerformed

    private void tfLNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfLNameActionPerformed
        // TODO add your handling code here:
        this.tfEmail.requestFocus();
    }//GEN-LAST:event_tfLNameActionPerformed

    private void tfEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfEmailActionPerformed
        // TODO add your handling code here:
        this.pfPass.requestFocus();
    }//GEN-LAST:event_tfEmailActionPerformed

    private void pfRePassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pfRePassActionPerformed
        // TODO add your handling code here:
        this.ckAgree.requestFocus();
    }//GEN-LAST:event_pfRePassActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LbEmail;
    private javax.swing.JLabel LbFName;
    private javax.swing.JLabel LbLName;
    private javax.swing.JLabel LbPass;
    private javax.swing.JLabel LbRePass;
    private javax.swing.JButton btDangKi;
    private javax.swing.JButton btResetMaKH;
    private javax.swing.JCheckBox ckAgree;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField pfPass;
    private javax.swing.JPasswordField pfRePass;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JTextField tfFName;
    private javax.swing.JTextField tfLName;
    private javax.swing.JTextField tfPatronID;
    // End of variables declaration//GEN-END:variables
}
