/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.DefaultListModel;
import javax.swing.JComboBox;
import model.Author;
import model.DetailBook;

/**
 *
 * @author coc
 */
public class fmTTSach extends javax.swing.JFrame {

    private String maSach;

    /**
     * Creates new form fmTTSach
     */
    public fmTTSach(String masach) {
        initComponents();
        this.maSach = masach;
        loadTTSach();
    }

    private void loadTTSach() {
        DetailBook debok = new DetailBook(this.maSach);
        this.lbTitleSach.setText(debok.getTitle());//ten sach
        this.lbTheLoai.setText(debok.getCate().getName());//the loai
        JComboBox<String> cmb = this.cmbTacGia;//tac gia
        for(Author au : debok.getAuthors()){
            cmb.addItem(au.getName());
        }
        //so luong ban sao
        Integer i = debok.getBookCopies().size();
        String s = "Số sách hiện có: " + i.toString();
        this.lbSoSachHienCo.setText(s);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbTitleSach = new javax.swing.JLabel();
        lbTheLoai = new javax.swing.JLabel();
        cmbTacGia = new javax.swing.JComboBox<>();
        lbSoSachHienCo = new javax.swing.JLabel();
        btLum = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Thông tin cuốn sách");

        lbTitleSach.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        lbTitleSach.setForeground(new java.awt.Color(255, 0, 51));
        lbTitleSach.setText("title sach");

        lbTheLoai.setText("the loai");

        cmbTacGia.setDoubleBuffered(true);
        cmbTacGia.setEditor(null);
        cmbTacGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTacGiaActionPerformed(evt);
            }
        });

        lbSoSachHienCo.setText("so luong sach hien tai");

        btLum.setText("Lụm nó và giỏ!");
        btLum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLumActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btLum, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER, false)
                        .addComponent(lbTitleSach, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbTheLoai, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmbTacGia, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbSoSachHienCo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)))
                .addContainerGap(152, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTitleSach)
                .addGap(18, 18, 18)
                .addComponent(cmbTacGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(lbTheLoai)
                .addGap(30, 30, 30)
                .addComponent(lbSoSachHienCo)
                .addGap(44, 44, 44)
                .addComponent(btLum)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btLumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btLumActionPerformed

    private void cmbTacGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTacGiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbTacGiaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btLum;
    private javax.swing.JComboBox<String> cmbTacGia;
    private javax.swing.JLabel lbSoSachHienCo;
    private javax.swing.JLabel lbTheLoai;
    private javax.swing.JLabel lbTitleSach;
    // End of variables declaration//GEN-END:variables

}
